Repository Curio-org/Curio, pull requests merged in 2023-10, with the labels that each got.

#51 replaced old logo with new logo, updated css properties
  src/components/Header/Header.tsx
  src/components/Header/header.css
Labels: design

#59 #56 Setup prettier for Curio
  .github/workflows/netlify.yml
  .prettierignore
  .vscode/settings.json
  README.md
  api/helloWorld.js
  api/sendMessage.js
  package-lock.json
  package.json
  postcss.config.js
  prettierrc.json
  public/index.html
  src/App.css
  src/App.tsx
  src/Awsup.tsx
  src/apis/youtube.tsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.tsx
  src/components/Footer/Twilio.css
  src/components/Footer/Twilio.tsx
  src/components/Header/Header.tsx
  src/components/Header/header.css
  src/components/Recorder/Recorder.css
  src/components/Recorder/Recorder.tsx
  src/components/Recorder/Recorder_old.js
  src/components/Recorder/UploadAudio.tsx
  src/components/Recorder/UploadAudio_old.js
  src/components/UnderHeader/APIError.css
  src/components/UnderHeader/APIError.tsx
  src/components/UnderHeader/Feature.css
  src/components/UnderHeader/Feature.tsx
  src/components/UnderHeader/SearchBar.css
  src/components/UnderHeader/Searchbar.tsx
  src/components/UnderHeader/UnderHeader.css
  src/components/UnderHeader/UnderHeader.tsx
  src/components/Video/Player.tsx
  src/components/Video/VideoItem.tsx
  src/components/Video/VideoList.tsx
  src/components/Video/translatedAudio.tsx
  src/components/Video/video.css
  src/components/assets/images/curio.png.d.ts
  src/components/comments/AddComment.scss
  src/components/comments/AddComment.tsx
  src/components/comments/Comment.scss
  src/components/comments/Comment.tsx
  src/components/comments/Comments.tsx
  src/components/comments/CommentsHeader.scss
  src/components/comments/CommentsHeader.tsx
  src/components/comments/shared.scss
  src/index.js
  src/style/styles.css
  tailwind.config.js
Labels: enhancement

#66 Add component tree
  README.md
Labels: documentation, difficulty: medium

#67 Add Navigation Functionality to Curio Logo
  package-lock.json
  src/components/Header/Header.tsx
Labels: UI/UX
